apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    description: Takes s2i Ruby image and adds some dependencies
    template.alpha.openshift.io/wait-for-ready: "true"
  labels:
    app: discourse
    template: discourse-template
  name: s2i-imagemagick-nodejs
spec:
  output:
    to:
      kind: ImageStreamTag
      name: s2i-imagemagick-nodejs:latest
  source:
    git:
      ref: {{ .Values.s2i_source_repository_ref }}
      uri: {{ .Values.s2i_source_repository_url }}
    type: Git
  strategy:
    dockerStrategy:
      noCache: true
    triggers:
    - type: ImageChange
    - type: ConfigChange
---
apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    description: Defines how to build the application
    template.alpha.openshift.io/wait-for-ready: "true"
  labels:
    app: discourse
    template: discourse-template
  name: {{ .Values.name }}
spec:
  output:
    to:
      kind: ImageStreamTag
      name: {{ .Values.name }}:latest
  source:
    contextDir: /
    git:
      ref: {{ .Values.source_repository_ref }}
      uri: {{ .Values.source_repository_url }}
    type: Git
  strategy:
    sourceStrategy:
      env:
      - name: DISCOURSE_HOSTNAME
        value: {{ .Values.application_domain }}
      - name: DISCOURSE_DB_HOST
        value: postgresql
      - name: DISCOURSE_DB_NAME
        value: {{ .Values.database_name }}
      - name: DISCOURSE_DB_USER
        valueFrom:
          secretKeyRef:
            key: database-user
            name: {{ .Values.name }}
      - name: DISCOURSE_DB_PASSWORD
        valueFrom:
          secretKeyRef:
            key: database-password
            name: {{ .Values.name }}
      - name: DISCOURSE_REDIS_PASSWORD
        valueFrom:
          secretKeyRef:
            key: redis-password
            name: {{ .Values.name }}
      - name: DISCOURSE_REDIS_HOST
        value: redis
      - name: RAILS_ENV
        value: production
      - name: RAILS_SERVE_STATIC_FILES
        value: "true"
      - name: DISCOURSE_SERVE_STATIC_ASSETS
        value: "true"
      - name: prometheus_trusted_ip_allowlist_regex
        value: {{ .Values.prometheus_domain }}
      from:
        kind: ImageStreamTag
        name: s2i-imagemagick-nodejs:latest
    type: Source
  triggers:
  - type: ImageChange
  - type: ConfigChange
