apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: discourse
    template: discourse-template
  name: discourse-uploads
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.discourse_data_volume_capacity }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: discourse
    template: discourse-template
  name: postgresql
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresql_volume_capacity }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: discourse
    template: discourse-template
  name: redis
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.redis_volume_capacity }}
