apiVersion: v1
kind: Route
metadata:
  labels:
    app: discourse
    template: discourse-template
  name: {{ .Values.name }}
spec:
  host: {{ .Values.application_domain }}
  to:
    kind: Service
    name: {{ .Values.name }}
