apiVersion: v1
kind: Secret
metadata:
  labels:
    app: discourse
    template: discourse-template
  name: {{ .Values.name }}
stringData:
  database-password: {{ .Values.database_password }}
  database-user: {{ .Values.database_user }}
  redis-password: {{ .Values.redis_password }}
  site-admin-password: {{ .Values.discourse_admin_emails_key }}
  site-admin-user: {{ .Values.discourse_admin_emails }}
  smtp-password: {{ .Values.smtp_password }}
  smtp-user: {{ .Values.smtp_user }}
