apiVersion: v1
kind: Service
metadata:
  annotations:
    description: Exposes and load balances the application pods
    service.alpha.openshift.io/dependencies: '[{"name": "postgresql", "kind": "Service"}]'
  labels:
    app: discourse
    template: discourse-template
  name: {{ .Values.name }}
spec:
  ports:
  - name: web
    port: 8080
    targetPort: 8081
  selector:
    name: {{ .Values.name }}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    description: Exposes the database server
  labels:
    app: discourse
    template: discourse-template
  name: postgresql
spec:
  ports:
  - name: postgresql
    port: 5432
    targetPort: 5432
  selector:
    name: postgresql
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: discourse
    template: discourse-template
  name: redis
spec:
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  selector:
    name: redis
